#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

# Get application name
application=$(getApplication)


runApplication blockMesh

runApplication setFields

runApplication $application

#------------------------------------------------------------------------------
